name: Capture HK Screenshot

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 오전 3시에 실행 (UTC 기준)
  workflow_dispatch:  # 수동으로 워크플로 실행할 수 있는 옵션

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # 최신 버전으로 업데이트

    - name: Set up Node.js
      uses: actions/setup-node@v3  # 최신 버전으로 업데이트
      with:
        node-version: '18'  # 최신 LTS 버전 사용

    - name: Install dependencies
      run: npm install

    - name: Run screenshot script
      run: node hk_screenshot.js

    - name: Commit screenshot
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add hk_screenshot.png
        git commit -m "Update HK screenshot"
        git push https://$GITHUB_TOKEN@github.com/clockmaker2020/selenium-screenshot-project.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
